# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export_image_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from qtpy import QtCore, QtGui, QtWidgets


class Ui_SaveImageDialog(object):
    def setupUi(self, SaveImageDialog):
        SaveImageDialog.setObjectName("SaveImageDialog")
        SaveImageDialog.resize(499, 282)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SaveImageDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(SaveImageDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.edit_name = QtWidgets.QLineEdit(SaveImageDialog)
        self.edit_name.setInputMask("")
        self.edit_name.setText("")
        self.edit_name.setObjectName("edit_name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_name)
        self.label_4 = QtWidgets.QLabel(SaveImageDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_path = QtWidgets.QLineEdit(SaveImageDialog)
        self.edit_path.setObjectName("edit_path")
        self.horizontalLayout.addWidget(self.edit_path)
        self.btn_path = QtWidgets.QPushButton(SaveImageDialog)
        self.btn_path.setObjectName("btn_path")
        self.horizontalLayout.addWidget(self.btn_path)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.groupBox = QtWidgets.QGroupBox(SaveImageDialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sb_width = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_width.sizePolicy().hasHeightForWidth())
        self.sb_width.setSizePolicy(sizePolicy)
        self.sb_width.setMinimum(1)
        self.sb_width.setMaximum(5000)
        self.sb_width.setSingleStep(1)
        self.sb_width.setProperty("value", 100)
        self.sb_width.setObjectName("sb_width")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sb_width)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.sp_heigth = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sp_heigth.sizePolicy().hasHeightForWidth())
        self.sp_heigth.setSizePolicy(sizePolicy)
        self.sp_heigth.setMinimum(1)
        self.sp_heigth.setMaximum(5000)
        self.sp_heigth.setSingleStep(1)
        self.sp_heigth.setProperty("value", 100)
        self.sp_heigth.setObjectName("sp_heigth")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sp_heigth)
        self.cb_keep_aspect = QtWidgets.QCheckBox(self.groupBox)
        self.cb_keep_aspect.setObjectName("cb_keep_aspect")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_keep_aspect)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_save = QtWidgets.QPushButton(SaveImageDialog)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.btn_cancel = QtWidgets.QPushButton(SaveImageDialog)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SaveImageDialog)
        self.btn_cancel.clicked.connect(SaveImageDialog.close)
        QtCore.QMetaObject.connectSlotsByName(SaveImageDialog)

    def retranslateUi(self, SaveImageDialog):
        _translate = QtCore.QCoreApplication.translate
        SaveImageDialog.setWindowTitle(_translate("SaveImageDialog", "Save Image"))
        self.label_3.setText(_translate("SaveImageDialog", "Name"))
        self.edit_name.setPlaceholderText(_translate("SaveImageDialog", "image.png"))
        self.label_4.setText(_translate("SaveImageDialog", "Path"))
        self.btn_path.setText(_translate("SaveImageDialog", "Choose"))
        self.groupBox.setTitle(_translate("SaveImageDialog", "Dimensions"))
        self.label.setText(_translate("SaveImageDialog", "Width"))
        self.sb_width.setSuffix(_translate("SaveImageDialog", " px"))
        self.label_2.setText(_translate("SaveImageDialog", "Height"))
        self.sp_heigth.setSuffix(_translate("SaveImageDialog", " px"))
        self.cb_keep_aspect.setText(_translate("SaveImageDialog", "Keep aspect ratio"))
        self.btn_save.setText(_translate("SaveImageDialog", "Save"))
        self.btn_cancel.setText(_translate("SaveImageDialog", "Cancel"))
from . import resources_rc
