#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
=====================================
Test for qplotutils.chart.interactive
=====================================



Autogenerated package stub.
"""
import unittest
import logging
import sys
import os
import numpy as np

from qtpy.QtCore import *
from qtpy.QtGui import *
from qtpy.QtOpenGL import *
from qtpy.QtWidgets import *

from qplotutils.chart.interactive import *

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.2"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"

_log = logging.getLogger(__name__)


class InteractiveChangeEventTests(unittest.TestCase):

    def setUp(self):
        """ Autogenerated. """
        pass
        
    def test_instantiate(self):
        """ Autogenerated. """
        obj = InteractiveChangeEvent()  # TODO: may fail!


class InteractiveVerticalLineTests(unittest.TestCase):

    def setUp(self):
        """ Autogenerated. """
        pass
        
    def test_instantiate(self):
        """ Autogenerated. """
        obj = InteractiveVerticalLine()  # TODO: may fail!