#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
===============================
Test for qplotutils.chart.color
===============================



Autogenerated package stub.
"""
import pytest
from pytestqt.qtbot import QtBot
import logging
import sys
import os
import numpy as np

from qtpy.QtCore import *
from qtpy.QtGui import *
from qtpy.QtOpenGL import *
from qtpy.QtWidgets import *

from qplotutils.chart.color import *

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.2"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"

_log = logging.getLogger(__name__)


class TestColormap(object):

    def test_Colormap__channel_gradient(self):
        """ Tests for Colormap__channel_gradient
        
        """
        # Autogenerated test skeleton for Colormap__channel_gradient
        pass

    def test__call__(self):
        """ Tests for _call__
        
        """
        # Autogenerated test skeleton for _call__
        pass


class TestNormalize(object):

    def test__call__(self):
        """ Tests for _call__
        
        """
        # Autogenerated test skeleton for _call__
        pass