#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
======================================
Test for qplotutils.chart.scatter_plot
======================================



Autogenerated package stub.
"""

import pytest
from pytestqt.qtbot import QtBot
import logging
import sys
import os
import numpy as np

from qtpy.QtCore import *
from qtpy.QtGui import *
from qtpy.QtOpenGL import *
from qtpy.QtWidgets import *

from qplotutils.chart.color import Colormap
from qplotutils.chart.scatter_plot import *

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.2"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"

_log = logging.getLogger(__name__)


@pytest.fixture()
def view(qtbot: QtBot):
    view = ChartView(orientation=ChartView.CARTESIAN)
    view.resize(800, 800)
    view.show()

    qtbot.addWidget(view)

    return view


DELAY = 50


class TestColorbar(object):
    def test_generatePicture(self):
        """ Tests for generatePicture
        
        """
        # Autogenerated test skeleton for generatePicture
        pass

    def test_updatePicture(self):
        """ Tests for updatePicture
        
        """
        # Autogenerated test skeleton for updatePicture
        pass

    def test_boundingRect(self):
        """ Tests for boundingRect
        
        """
        # Autogenerated test skeleton for boundingRect
        pass

    def test_paint(self):
        """ Tests for paint
        
        """
        # Autogenerated test skeleton for paint
        pass


class TestScatterItem(object):
    def test_boundingRect(self):
        """ Tests for boundingRect
        
        """
        # Autogenerated test skeleton for boundingRect
        pass

    def test_paint(self):
        """ Tests for paint
        
        """
        # Autogenerated test skeleton for paint
        pass

    def test_shape(self):
        """ Tests for shape
        
        """
        # Autogenerated test skeleton for shape
        pass

    def test_updatePicture(self):
        """ Tests for updatePicture
        
        """
        # Autogenerated test skeleton for updatePicture
        pass


class TestScatterPlotView(object):
    def test_scatter_plots(self, qtbot: QtBot):
        # First dock
        cm_01 = Colormap()
        view_01 = ScatterPlotView(cm_01)
        qtbot.add_widget(view_01)

        s = ScatterItem(0, 3, -1)
        view_01.addItem(s)
        view_01.show()
        # dock_01 = Dock(title="Add items dynamic range")
        # dock_01.addWidget(view_01)
        # bench.addDock(dock_01)

        items = []
        for k in range(100):
            s = ScatterItem(
                np.random.randint(-100, 100), np.random.randint(-100, 100), k
            )
            items.append(s)

        view_01.addItems(items)
        view_01.autoRange()
        qtbot.wait(DELAY)

    def test_ScatterPlotView__colormap_callback(self, qtbot: QtBot):
        """ Tests for ScatterPlotView__colormap_callback

        """
        # Autogenerated test skeleton for ScatterPlotView__colormap_callback
        pass

    def test_addItem(self, qtbot: QtBot):
        """ Tests for addItem

        """
        # Autogenerated test skeleton for addItem
        pass

    def test_addItems(self, qtbot: QtBot):
        """ Tests for addItems

        """
        # Autogenerated test skeleton for addItems
        pass
