#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
=====================================
Test for qplotutils.chart.interactive
=====================================



Autogenerated package stub.
"""
import pytest
from pytestqt.qtbot import QtBot
import logging
import sys
import os
import numpy as np

from qtpy.QtCore import *
from qtpy.QtGui import *
from qtpy.QtOpenGL import *
from qtpy.QtWidgets import *

from qplotutils.chart.interactive import *

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.2"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"

_log = logging.getLogger(__name__)


class TestInteractiveChangeEvent(object):
    # autogenerator: no functions found
    pass


class TestInteractiveVerticalLine(object):

    def test_hoverEnterEvent(self):
        """ Tests for hoverEnterEvent
        
        """
        # Autogenerated test skeleton for hoverEnterEvent
        pass

    def test_hoverLeaveEvent(self):
        """ Tests for hoverLeaveEvent
        
        """
        # Autogenerated test skeleton for hoverLeaveEvent
        pass

    def test_itemChange(self):
        """ Tests for itemChange
        
        """
        # Autogenerated test skeleton for itemChange
        pass

    def test_label(self):
        """ Tests for label
        
        """
        # Autogenerated test skeleton for label
        pass

    def test_paint(self):
        """ Tests for paint
        
        """
        # Autogenerated test skeleton for paint
        pass

    def test_setX(self):
        """ Tests for setX
        
        """
        # Autogenerated test skeleton for setX
        pass

    def test_visibleRangeChanged(self):
        """ Tests for visibleRangeChanged
        
        """
        # Autogenerated test skeleton for visibleRangeChanged
        pass