#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
===============================
Test for qplotutils.chart.items
===============================



Autogenerated package stub.
"""
import pytest
from pytestqt.qtbot import QtBot
import logging
import sys
import os
import numpy as np

from qtpy.QtCore import *
from qtpy.QtGui import *
from qtpy.QtOpenGL import *
from qtpy.QtWidgets import *

from qplotutils.chart.items import *
from qplotutils.chart.view import ChartView

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.2"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"

_log = logging.getLogger(__name__)


@pytest.fixture()
def view(qtbot: QtBot):
    view = ChartView(orientation=ChartView.CARTESIAN)
    view.resize(800, 800)
    view.show()

    qtbot.addWidget(view)

    return view


DELAY = 50


class TestBaseMixin(object):
    def test_chartItemFlags(self):
        """ Tests for chartItemFlags
        
        """
        # Autogenerated test skeleton for chartItemFlags
        pass

    def test_color(self):
        """ Tests for color
        
        """
        # Autogenerated test skeleton for color
        pass

    def test_label(self):
        """ Tests for label
        
        """
        # Autogenerated test skeleton for label
        pass

    def test_visibleRangeChanged(self):
        """ Tests for visibleRangeChanged
        
        """
        # Autogenerated test skeleton for visibleRangeChanged
        pass


class TestChartItem(object):
    def test_boundingRect(self):
        """ Tests for boundingRect
        
        """
        # Autogenerated test skeleton for boundingRect
        pass

    def test_paint(self):
        """ Tests for paint
        
        """
        # Autogenerated test skeleton for paint
        pass


class TestChartItemFlags(object):
    # autogenerator: no functions found
    pass


class TestChartItemGroup(object):
    # autogenerator: no functions found
    pass


class TestChartWidgetItem(object):
    def test_boundingRect(self):
        """ Tests for boundingRect
        
        """
        # Autogenerated test skeleton for boundingRect
        pass


class TestColorSet(object):
    # autogenerator: no functions found
    pass


class TestCoordCross(object):
    def test_boundingRect(self, view: ChartView, qtbot: QtBot):
        """ Tests for boundingRect
        
        """
        c = CoordCross()
        view.addItem(c)

        qtbot.wait(DELAY)

    def test_paint(self):
        """ Tests for paint
        
        """
        # Autogenerated test skeleton for paint
        pass


class TestHLine(object):
    def test_label(self):
        """ Tests for label
        
        """
        # Autogenerated test skeleton for label
        pass

    def test_paint(self):
        """ Tests for paint
        
        """
        # Autogenerated test skeleton for paint
        pass

    def test_setY(self):
        """ Tests for setY
        
        """
        # Autogenerated test skeleton for setY
        pass

    def test_visibleRangeChanged(self):
        """ Tests for visibleRangeChanged
        
        """
        # Autogenerated test skeleton for visibleRangeChanged
        pass


class TestLineChartItem(object):
    def test_makePath(self):
        """ Tests for makePath
        
        """
        # Autogenerated test skeleton for makePath
        pass

    def test_abscissa(self):
        """ Tests for abscissa
        
        """
        # Autogenerated test skeleton for abscissa
        pass

    def test_boundingRect(self):
        """ Tests for boundingRect
        
        """
        # Autogenerated test skeleton for boundingRect
        pass

    def test_label(self):
        """ Tests for label
        
        """
        # Autogenerated test skeleton for label
        pass

    def test_ordinate(self):
        """ Tests for ordinate
        
        """
        # Autogenerated test skeleton for ordinate
        pass

    def test_paint(self):
        """ Tests for paint
        
        """
        # Autogenerated test skeleton for paint
        pass

    def test_plot(self):
        """ Tests for plot
        
        """
        # Autogenerated test skeleton for plot
        pass

    def test_showTicks(self):
        """ Tests for showTicks
        
        """
        # Autogenerated test skeleton for showTicks
        pass

    def test_visibleRangeChanged(self):
        """ Tests for visibleRangeChanged
        
        """
        # Autogenerated test skeleton for visibleRangeChanged
        pass


class TestRectMarker(object):
    def test_boundingRect(self):
        """ Tests for boundingRect
        
        """
        # Autogenerated test skeleton for boundingRect
        pass

    def test_paint(self):
        """ Tests for paint
        
        """
        # Autogenerated test skeleton for paint
        pass


class TestTextItem(object):
    def test_boundingRect(self, view: ChartView, qtbot: QtBot):
        """ Tests for boundingRect
        
        """
        ti = TextItem(QPoint(0, 0), "Foo")
        view.addItem(ti)

        qtbot.wait(DELAY)

    def test_paint(self):
        """ Tests for paint
        
        """
        # Autogenerated test skeleton for paint
        pass


class TestVLine(object):
    def test_label(self):
        """ Tests for label
        
        """
        # Autogenerated test skeleton for label
        pass

    def test_paint(self):
        """ Tests for paint
        
        """
        # Autogenerated test skeleton for paint
        pass

    def test_setX(self):
        """ Tests for setX
        
        """
        # Autogenerated test skeleton for setX
        pass

    def test_visibleRangeChanged(self):
        """ Tests for visibleRangeChanged
        
        """
        # Autogenerated test skeleton for visibleRangeChanged
        pass
