#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
========================================
Test for qplotutils.wireframe.base_types
========================================



Autogenerated package stub.
"""
import pytest
from pytestqt.qtbot import QtBot
import logging
import sys
import os
import numpy as np

from qtpy.QtCore import *
from qtpy.QtGui import *
from qtpy.QtOpenGL import *
from qtpy.QtWidgets import *

from qplotutils.wireframe.base_types import *

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.2"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"

_log = logging.getLogger(__name__)


class TestDefaultGlOptions(object):
    # autogenerator: no functions found
    pass


class TestVector3d(object):

    def test__new__(self):
        """ Tests for _new__
        
        """
        # Autogenerated test skeleton for _new__
        pass

    def test__str__(self):
        """ Tests for _str__
        
        """
        # Autogenerated test skeleton for _str__
        pass

    def test_cross(self):
        """ Tests for cross
        
        """
        # Autogenerated test skeleton for cross
        pass

    def test_norm(self):
        """ Tests for norm
        
        """
        # Autogenerated test skeleton for norm
        pass

    def test_normalize(self):
        """ Tests for normalize
        
        """
        # Autogenerated test skeleton for normalize
        pass

    def test_x(self):
        """ Tests for x
        
        """
        # Autogenerated test skeleton for x
        pass

    def test_y(self):
        """ Tests for y
        
        """
        # Autogenerated test skeleton for y
        pass

    def test_z(self):
        """ Tests for z
        
        """
        # Autogenerated test skeleton for z
        pass