#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
=========================================
Test for qplotutils.wireframe.cam_control
=========================================



Autogenerated package stub.
"""
import pytest
from pytestqt.qtbot import QtBot
import logging
import sys
import os
import numpy as np

from qtpy.QtCore import *
from qtpy.QtGui import *
from qtpy.QtOpenGL import *
from qtpy.QtWidgets import *

from qplotutils.wireframe.cam_control import *

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.2"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"

_log = logging.getLogger(__name__)


class TestCamControl(object):

    def test_cam_changed(self, qtbot: QtBot):
        """ Tests for cam_changed

        """
        # Autogenerated test skeleton for cam_changed
        pass

    def test_dial_azimuth_changed(self, qtbot: QtBot):
        """ Tests for dial_azimuth_changed

        """
        # Autogenerated test skeleton for dial_azimuth_changed
        pass

    def test_dial_distance_changed(self, qtbot: QtBot):
        """ Tests for dial_distance_changed

        """
        # Autogenerated test skeleton for dial_distance_changed
        pass

    def test_dial_elevation_changed(self, qtbot: QtBot):
        """ Tests for dial_elevation_changed

        """
        # Autogenerated test skeleton for dial_elevation_changed
        pass

    def test_edit_distance_changed(self, qtbot: QtBot):
        """ Tests for edit_distance_changed

        """
        # Autogenerated test skeleton for edit_distance_changed
        pass