#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
==================================
Test for qplotutils.wireframe.view
==================================



Autogenerated package stub.
"""
import pytest
from pytestqt.qtbot import QtBot
import logging
import sys
import os
import numpy as np

from qtpy.QtCore import *
from qtpy.QtGui import *
from qtpy.QtOpenGL import *
from qtpy.QtWidgets import *

from qplotutils.wireframe.view import *

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.2"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"

_log = logging.getLogger(__name__)


class TestChartView3d(object):

    def test_addItem(self, qtbot: QtBot):
        """ Tests for addItem

        """
        # Autogenerated test skeleton for addItem
        pass

    def test_cameraPosition(self, qtbot: QtBot):
        """ Tests for cameraPosition

        """
        # Autogenerated test skeleton for cameraPosition
        pass

    def test_camera_update(self, qtbot: QtBot):
        """ Tests for camera_update

        """
        # Autogenerated test skeleton for camera_update
        pass

    def test_drawItemTree(self, qtbot: QtBot):
        """ Tests for drawItemTree

        """
        # Autogenerated test skeleton for drawItemTree
        pass

    def test_getViewport(self, qtbot: QtBot):
        """ Tests for getViewport

        """
        # Autogenerated test skeleton for getViewport
        pass

    def test_initializeGL(self, qtbot: QtBot):
        """ Tests for initializeGL

        """
        # Autogenerated test skeleton for initializeGL
        pass

    def test_keyReleaseEvent(self, qtbot: QtBot):
        """ Tests for keyReleaseEvent

        """
        # Autogenerated test skeleton for keyReleaseEvent
        pass

    def test_mouseMoveEvent(self, qtbot: QtBot):
        """ Tests for mouseMoveEvent

        """
        # Autogenerated test skeleton for mouseMoveEvent
        pass

    def test_mousePressEvent(self, qtbot: QtBot):
        """ Tests for mousePressEvent

        """
        # Autogenerated test skeleton for mousePressEvent
        pass

    def test_orbit(self, qtbot: QtBot):
        """ Tests for orbit

        """
        # Autogenerated test skeleton for orbit
        pass

    def test_paintGL(self, qtbot: QtBot):
        """ Tests for paintGL

        """
        # Autogenerated test skeleton for paintGL
        pass

    def test_pan(self, qtbot: QtBot):
        """ Tests for pan

        """
        # Autogenerated test skeleton for pan
        pass

    def test_pixelSize(self, qtbot: QtBot):
        """ Tests for pixelSize

        """
        # Autogenerated test skeleton for pixelSize
        pass

    def test_projectionMatrix(self, qtbot: QtBot):
        """ Tests for projectionMatrix

        """
        # Autogenerated test skeleton for projectionMatrix
        pass

    def test_removeItem(self, qtbot: QtBot):
        """ Tests for removeItem

        """
        # Autogenerated test skeleton for removeItem
        pass

    def test_resizeGL(self, qtbot: QtBot):
        """ Tests for resizeGL

        """
        # Autogenerated test skeleton for resizeGL
        pass

    def test_setCameraPosition(self, qtbot: QtBot):
        """ Tests for setCameraPosition

        """
        # Autogenerated test skeleton for setCameraPosition
        pass

    def test_setModelview(self, qtbot: QtBot):
        """ Tests for setModelview

        """
        # Autogenerated test skeleton for setModelview
        pass

    def test_setProjection(self, qtbot: QtBot):
        """ Tests for setProjection

        """
        # Autogenerated test skeleton for setProjection
        pass

    def test_viewMatrix(self, qtbot: QtBot):
        """ Tests for viewMatrix

        """
        # Autogenerated test skeleton for viewMatrix
        pass

    def test_wheelEvent(self, qtbot: QtBot):
        """ Tests for wheelEvent

        """
        # Autogenerated test skeleton for wheelEvent
        pass


class TestViewProperties(object):

    def test_azimuth_angle(self, qtbot: QtBot):
        """ Tests for azimuth_angle

        """
        # Autogenerated test skeleton for azimuth_angle
        pass

    def test_center(self, qtbot: QtBot):
        """ Tests for center

        """
        # Autogenerated test skeleton for center
        pass

    def test_distance(self, qtbot: QtBot):
        """ Tests for distance

        """
        # Autogenerated test skeleton for distance
        pass

    def test_elevation_angle(self, qtbot: QtBot):
        """ Tests for elevation_angle

        """
        # Autogenerated test skeleton for elevation_angle
        pass

    def test_fov(self, qtbot: QtBot):
        """ Tests for fov

        """
        # Autogenerated test skeleton for fov
        pass