#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
====================================
Test for qplotutils.wireframe.shader
====================================



Autogenerated package stub.
"""
import pytest
from pytestqt.qtbot import QtBot
import logging
import sys
import os
import numpy as np

from qtpy.QtCore import *
from qtpy.QtGui import *
from qtpy.QtOpenGL import *
from qtpy.QtWidgets import *

from qplotutils.wireframe.shader import *

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.2"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"

_log = logging.getLogger(__name__)


class TestShaderProgram(object):

    def test__enter__(self):
        """ Tests for _enter__
        
        """
        # Autogenerated test skeleton for _enter__
        pass

    def test__exit__(self):
        """ Tests for _exit__
        
        """
        # Autogenerated test skeleton for _exit__
        pass

    def test_compile(self):
        """ Tests for compile
        
        """
        # Autogenerated test skeleton for compile
        pass

    def test_glOptions(self):
        """ Tests for glOptions
        
        """
        # Autogenerated test skeleton for glOptions
        pass

    def test_name(self):
        """ Tests for name
        
        """
        # Autogenerated test skeleton for name
        pass

    def test_program(self):
        """ Tests for program
        
        """
        # Autogenerated test skeleton for program
        pass

    def test_uniform(self):
        """ Tests for uniform
        
        """
        # Autogenerated test skeleton for uniform
        pass


class TestShaderRegistry(object):

    def test__getitem__(self):
        """ Tests for _getitem__
        
        """
        # Autogenerated test skeleton for _getitem__
        pass

    def test_add(self):
        """ Tests for add
        
        """
        # Autogenerated test skeleton for add
        pass