#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
=========================================
Test for qplotutils.wireframe.cam_control
=========================================



Autogenerated package stub.
"""
import unittest
import logging
import sys
import os
import numpy as np

from qtpy.QtCore import *
from qtpy.QtGui import *
from qtpy.QtOpenGL import *
from qtpy.QtWidgets import *

from qplotutils.wireframe.cam_control import *
from qplotutils.wireframe.view import ViewProperties

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.2"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"

_log = logging.getLogger(__name__)


class CamControlTests(unittest.TestCase):

    app = None

    @classmethod
    def setUpClass(cls):
        cls.app = QApplication([])

    def setUp(self):
        """ Autogenerated. """
        pass
        
    def test_instantiate(self):
        """ Autogenerated. """
        obj = CamControl(ViewProperties())  # TODO: may fail!