#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
============================
Tests for package qplotutils
============================



Autogenerated module stub.
"""
import logging

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.1"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"