import pytest
from pytestqt.qtbot import QtBot

from qtpy.QtCore import *
from qtpy.QtGui import *
from qtpy.QtOpenGL import *
from qtpy.QtWidgets import *

from qplotutils.bench import *

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.2"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"

_log = logging.getLogger(__name__)

#
# @pytest.fixture()
# def init_qapp():
#     app = QApplication([])
#     return app



class TestDock(object):


    # Autogenerated test skeleton for addWidget
    def test_addWidget(self, qtbot : QtBot):
        """ Tests for addWidget

        """
        dut = Dock()

        widget = QWidget()
        dut.addWidget(widget)

        qtbot.mouseClick(dut, Qt.LeftButton)
        assert dut.was_clicked == 1
        # assert self.dut.layout().count() == 1

        qtbot.mouseClick(dut, Qt.LeftButton)
        assert dut.was_clicked == 2

        qtbot.mouseClick(dut, Qt.LeftButton)
        assert dut.was_clicked == 3