"""
=========================
Test for qplotutils.bench
=========================



Autogenerated package stub.
"""
import pytest
from pytestqt.qtbot import QtBot
import logging
import sys
import os
import numpy as np
import tempfile

from qtpy.QtCore import *
from qtpy.QtGui import *
from qtpy.QtOpenGL import *
from qtpy.QtWidgets import *

from qplotutils import Configuration

PKG_DIR = os.path.abspath(os.path.join(__file__, "..", "..", ".."))
print(PKG_DIR)
if PKG_DIR not in sys.path:
    sys.path.append(PKG_DIR)


from qplotutils.chart.items import LineChartItem
from qplotutils.chart.view import ChartView
from qplotutils.wireframe.items import CoordinateCross, MeshItem, Mesh, Grid
from qplotutils.wireframe.view import ChartView3d
from qplotutils.bench import *

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.2"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"

_log = logging.getLogger(__name__)


DISPLAY_LENGTH = 200  # ms


@pytest.fixture()
def dut(qtbot: QtBot):

    dut = Bench()
    qtbot.addWidget(dut)
    dut.resize(800, 800)
    dut.show()
    return dut


class TestConfiguration(object):
    def test_init(self):
        cfg1 = Configuration()
        cfg2 = Configuration()

        cfg2.debug = True
        assert cfg1.debug == True

        cfg2.debug = False
        assert cfg1.debug == False

        cfg2.debug_layout = True
        assert cfg1.debug_layout == True

        cfg2.debug_layout = False
        assert cfg1.debug_layout == False
