#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
==========================
Test for qplotutils.player
==========================



Autogenerated package stub.
"""
import pytest
from pytestqt.qtbot import QtBot
import logging
import sys
import os
import numpy as np

from qtpy.QtCore import *
from qtpy.QtGui import *
from qtpy.QtOpenGL import *
from qtpy.QtWidgets import *

from qplotutils.player import *

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.2"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"

_log = logging.getLogger(__name__)


@pytest.fixture()
def player(qtbot: QtBot):
    p = PlaybackWidget()
    p.show()
    qtbot.addWidget(p)

    p.timestamps = np.arange(0, 1000, 12) * 141000

    return p


DELAY = 200


class TestPlaybackWidget(object):
    def test_slider_pressed(self, player: PlaybackWidget, qtbot: QtBot):
        """ Tests for slider_pressed

        """
        # player.ui.slider_index.setValue(10)
        pass

    def test_slider_value_changed(self, qtbot: QtBot):
        """ Tests for slider_value_changed

        """
        # Autogenerated test skeleton for slider_value_changed
        pass

    def test_advance(self, player: PlaybackWidget, qtbot: QtBot):
        """ Tests for advance

        """
        # player.advance()
        # player.advance(reverse=True)
        pass

    def test_debug_slider(self, qtbot: QtBot):
        """ Tests for debug_slider

        """
        # Autogenerated test skeleton for debug_slider
        pass

    def test_jump_to_timestamp(self, qtbot: QtBot):
        """ Tests for jump_to_timestamp

        """
        # Autogenerated test skeleton for jump_to_timestamp
        pass

    def test_pause(self, qtbot: QtBot):
        """ Tests for pause

        """
        # Autogenerated test skeleton for pause
        pass

    def test_play(self, qtbot: QtBot):
        """ Tests for play

        """
        # Autogenerated test skeleton for play
        pass

    def test_play_pause(self, qtbot: QtBot):
        """ Tests for play_pause

        """
        # Autogenerated test skeleton for play_pause
        pass

    def test_step_back(self, qtbot: QtBot):
        """ Tests for step_back

        """
        # Autogenerated test skeleton for step_back
        pass

    def test_step_forward(self, qtbot: QtBot):
        """ Tests for step_forward

        """
        # Autogenerated test skeleton for step_forward
        pass

    def test_timestamps(self, qtbot: QtBot):
        """ Tests for timestamps

        """
        # Autogenerated test skeleton for timestamps
        pass
