#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
===============================
Tests for package qplotutils.ui
===============================



Autogenerated module stub.
"""
import logging

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.2"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"
