#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
===============================
Test for qplotutils.ui.playback
===============================



Autogenerated package stub.
"""
import pytest
from pytestqt.qtbot import QtBot
import logging
import sys
import os
import numpy as np

from qtpy.QtCore import *
from qtpy.QtGui import *
from qtpy.QtOpenGL import *
from qtpy.QtWidgets import *

from qplotutils.ui.playback import *

__author__ = "Philipp Baust"
__copyright__ = "Copyright 2019, Philipp Baust"
__credits__ = []
__license__ = "MIT"
__version__ = "0.0.2"
__maintainer__ = "Philipp Baust"
__email__ = "philipp.baust@gmail.com"
__status__ = "Development"

_log = logging.getLogger(__name__)


class TestUi_PlaybackControl(object):

    def test_retranslateUi(self):
        """ Tests for retranslateUi
        
        """
        # Autogenerated test skeleton for retranslateUi
        pass

    def test_setupUi(self):
        """ Tests for setupUi
        
        """
        # Autogenerated test skeleton for setupUi
        pass